### ISSUE TITLE
"Crunchyroll" is not a internal command

### ISSUE THREAD

**Issue by kirz0** [UnattendedFlight/Sonders-Crunchyroll-Downloader#12]
When a try download something it keeps says "Crunchyroll is not a internal command" and doesn't work.

**Comment by UnattendedFlight** [comment]
This was an error on my end, i had not changed the way of downloading in the batch file like i did in the installer. So it basically installed crunchy.js, and the batch file wanted to use crunchyroll.js.. I have fixed it now. #12

You can fix this problem by performing either of the two actions below:

Either
- 1 Go to the installation folder of the downloader and replace the ".bat" file there with the one downloaded from [here](http://adsva.org/d/Application%20Files/CR%20Downloader%20Project%20Files/BCKUP/newest/1.7/CR%20Downloader.bat, "Fix for 
#12")

or

- 2 Run the installation program again and it will fix itself

**Comment by UnattendedFlight** [comment]
Please tell me if the problem has been fixed, and i will close this issue.

**Comment by kirz0** [comment]
I run the installation again, it says downloading and then shuts down automatically without downloading anything. The same happens with the ".bat" of your link.

**Comment by UnattendedFlight** [comment]
@kirz0 Does it say anything else? Please give me more details about this problem so i can help more efficiently. First, I'll ask some questions:

1. Do you have a Crunchyroll premium account?
2. Are you sure that [Node.Js](https://nodejs.org/dist/v6.8.1/node-v6.8.1-x64.msi) is correctly installed?
3. Are you sure you entered the right username and password to your Crunchyroll account?
4. Did you write the link in the right format?
5. Did you write in the outputfolder in the right format?

### How to know:
1. Do you recall ever purchasing premium for crunchyroll within the last month or so? (Check bank statement)
2. Run `npm` in CMD, if there are no errors, it is installed fine.
3. If you chose to save the password, you can doublecheck if you did by editing the "Desktop.ini" file located in the installation folder or launch folder. If you chose it to not remember, please delete the "Settings.ini" file and start the downloader again. You will then have to enter login details again, then type `Y` when it asks you to save it. Or else it wont work. However, ill push an update soon so this will be false.

4. The correct crunchyroll link should look like this:
`http://www.crunchyroll.com/gintama`
5. No quotations, just the folder. Like this:
`Z:\Folder\AnotherFolder\Hentai`
It doesn't matter if there are spaces:
`X:\AnotherOne\Another One\A N O T H E R O N E`
Leave the last`\` out.

For some reason, if you choose it to not remember your password, it wont ask for it when you try to download in every session. So it outputs the password to the downloader as: `ECHO is off`. This just causes the downloader to quit like you described.

## One more thing. 
Please edit the created "Downloader.bat" and remove your username and password, then send me all the code contained in the batch file. There might be some scripting error. 
However, i just tried to download, and it worked fine:
### Screenshot [HERE](http://prntscr.com/cve7zn)

**Comment by kirz0** [comment]
My account is 15 days premium trial, could the problem be there?

I also noted when i try to download single links, without batch, it says this:
`:start
cls
echo.
echo -----------------------------------------
echo.
echo 	   Welcome to Sonder's CR				Logged in as johadr
echo            downloader                      Current Path: U:\Uppload\Anime Serier
echo.
echo -----------------------------------------
echo.
echo.
echo To be downloaded:
type %kti%.txt
echo READY [==========]
echo.
echo -----------------------------------------
echo Downloading:
echo.
crunchy -o "%pth%" -u %usr% -p %psw% %url%
if ErrorLevel 0 goto exit
goto start`
My data is automatically changed for that in the code. My usarname is altered for johadr and my "Current Path" is also altered for that in the code. Is this normal?

**Comment by kirz0** [comment]
I run `npm` in CMD and it gave my [this](http://prntscr.com/cvfran).

**Comment by UnattendedFlight** [comment]
@kirz0 Regarding the code

```
:start
cls
echo.
echo -----------------------------------------
echo.
echo 	   Welcome to Sonder's CR				Logged in as johadr
echo            downloader                      Current Path: U:\Uppload\Anime Serier
echo.
echo -----------------------------------------
echo.
echo.
echo To be downloaded:
type %kti%.txt
echo READY [==========]
echo.
echo -----------------------------------------
echo Downloading:
echo.
crunchy -o "%pth%" -u %usr% -p %psw% %url%
if ErrorLevel 0 goto exit
goto start
```

Never mind that. The code should still be functional since it doesnt really change the variables but just displays some text. It is just leftovers from a few direct tests that I've done to the program.

Npm seems to be installed. So that's a good thing.

I've never tried to download through a trial before, but by the looks of [this](http://prntscr.com/cvg644) it seems that you are required to have a premium account.

## Don't worry

If you want to, I'll download whatever series you would like and make it available to you through a private download or through plex aight?

Reply with any sort of agreement, and I'll close this issue.

Contact me on my discord for additional help: [Discord](https://discord.gg/BBgQPSy)

**Comment by kirz0** [comment]
You can close this issue. But my account despite being trial it remains premium.

**Comment by UnattendedFlight** [comment]
Okay, 

> But my account despite being trial it remains premium.

What does this mean?

**Comment by kirz0** [comment]
[This](http://prntscr.com/cvgey7), it's a premium trial, but i have the privileges of a premium user.

**Comment by UnattendedFlight** [comment]
Hmm, yeah. Your status is updated to premium. But i dont quite know how or why the downloader then don't work. 

For a possible fix, please go to cmd and type in:
`npm install -g crunchy`
and try another crunchyroll link or the same one.
